
env_variables:
  GCLOUD_PROJECT: 'app-hotel-308617'

runtime: python39
runtime_config:
    python_version: 3

# Machine config  https://cloud.google.com/appengine/docs/standard
instance_class: B2
manual_scaling:
  instances: 2

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10

entrypoint: gunicorn -b :$PORT main:app.server --timeout 60 --workers 1

# Instance name
service: app-hotel-308617
handlers:
  - url: /.*
    script: auto
    secure: always